"""Change name column in profiles table to last_name

Revision ID: 793ab0a8c605
Revises: c206bc885fbe
Create Date: 2026-01-17 17:33:01.097437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "793ab0a8c605"
down_revision: Union[str, Sequence[str], None] = "c206bc885fbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("last_name", sa.String(length=40), nullable=True)
    )
    op.drop_column("profiles", "second_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("second_name", sa.VARCHAR(length=40), nullable=True)
    )
    op.drop_column("profiles", "last_name")
    # ### end Alembic commands ###
